# Generated by Django 4.2.19 on 2025-03-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号码')),
                ('classmate', models.CharField(db_column='class', default='', max_length=50, verbose_name='班级编号')),
                ('description', models.TextField(null=True, verbose_name='个性签名')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '未入学'), (2, '已毕业')], default=0, verbose_name='学生状态')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student',
            },
        ),
    ]
